title: 401-MGY
description: The story of Titanic
url: "https://www.401mgy.com"
author: Rodney

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

collections:
  articles:
    output: true
    permalink: /articles/:name/
